#!/usr/bin/env python3
"""What has actually been read of each paper, across every receipt in this checkout.

🔴 WHY THIS IS A VIEW AND NOT AN EVENT
--------------------------------------
On 2026-08-10 two actors read `PMID 42422765` in parallel, at 10:17 and 12:19, and both
legitimately continued the same earlier receipt. Their coverage maps differ. After the merge a
reader following the ledger sees the LAST receipt and takes it for the state of that paper —
so whichever actor finished second silently erases what the other read.

The fix is to sum, never to choose. But the sum cannot be a receipt, for three reasons that
are each sufficient:

  - **It has no author.** The only session present at a merge is the integrator, who has read
    nothing. A receipt signed by a process rather than a reader is a fabricated attestation.
  - **The ledger records what happened.** No reading happens at a merge. An event declaring
    "I combine two readings" is a register operation dressed as an act of reading, and the
    chain cannot tell those apart — the same confusion between lineage and register order that
    forced `prior_receipt` to change.
  - **A receipt must never assert something its author did not do.** The union is true of the
    SYSTEM and false as a description of any single reading.

So it is derived, and it is committed — like `coverage_report.md`, which drifted this same day
and whose drift test caught it. A view calculated on demand has no stable answer for anyone
who does not run the tool, which is the defect the committed form exists to avoid.

🔴 PER CHECKOUT, AND IT SAYS SO
-------------------------------
Nothing here counts across branches and nothing should: a count over unmerged state is a count
of work that is not in the model. This view is true of the checkout that generated it, and the
page declares that in its own header rather than leaving a reader to assume otherwise — the
same ambiguity `locator_audit` had to split when `unauditable` covered both "no surface
exists" and "no surface HERE".
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fulltext_receipts as receipts  # noqa: E402

# How coverage states combine when two readings of one paper are summed. Higher wins, and the
# order is what a reader would ask for: an image inspected beats a caption skimmed, and both
# beat not having looked. `not_present` and `unavailable` are facts about the ARTICLE rather
# than about the reading, so they lose to any state that reports someone looking — except
# `not_read`, which they outrank because "there is no supplement" answers the question and
# "nobody opened it" does not.
COVERAGE_RANK = {
    "unknown_legacy": 0,
    "not_read": 1,
    "unavailable": 2,
    "not_present": 3,
    "captions_only": 4,
    "read": 5,
}
SECTION_ORDER = [
    "abstract", "introduction", "methods", "results", "figures", "tables",
    "discussion", "limitations", "supplementary", "references",
]
HEADER = """<!-- GENERATED by framework/scripts/reading_state.py — do not hand-edit. -->
# Reading state — the union of every receipt, per paper

**Derived, not canonical.** Regenerate with:

```bash
python3 framework/scripts/reading_state.py --out disease-models/{disease}/registries/reading_state.md
```

🔴 **This page is true of ONE checkout — the one that generated it.** It counts the receipts in
this tree's ledger and nothing else. Work sitting on an unmerged branch is not here, and a
count over unmerged state is a count of work that is not in the model. If a paper looks
unread, check whether the reading is merged before concluding it does not exist.

🔴 **Why a union, and why nobody signs it.** Two actors can read one paper in parallel and both
be right; the later receipt is not a correction of the earlier one. Reading the last receipt as
the state of a paper silently erases whatever the other reader covered. The union is true of
the system and false as a description of any single reading — so it is computed here and
asserted by no receipt. `prior_receipt` means the reading this one builds on, and siblings
sharing a parent are the normal case under parallel branches.
"""


def rank(state: str) -> int:
    return COVERAGE_RANK.get(state, 0)


def study_key(receipt: dict) -> str:
    pmid = str(receipt.get("study_id", {}).get("pmid") or "").strip()
    if pmid:
        return f"PMID {pmid}"
    doi = receipts.normalise_doi(receipt.get("study_id", {}).get("doi"))
    return f"DOI {doi}" if doi else "UNIDENTIFIED"


def summarise(ledger: list[dict]) -> list[dict]:
    by_study: dict[str, list[dict]] = {}
    for receipt in ledger:
        by_study.setdefault(study_key(receipt), []).append(receipt)

    rows = []
    for key, group in sorted(by_study.items()):
        union: dict[str, str] = {}
        for receipt in group:
            for section, state in (receipt.get("coverage") or {}).items():
                if section not in union or rank(state) > rank(union[section]):
                    union[section] = state
        # A FORK is two receipts naming the same parent. It is reported rather than resolved:
        # the ledger cannot tell parallel work from a correction, and a reader can.
        parents: dict[str, list[str]] = {}
        for receipt in group:
            parent = receipt.get("prior_receipt")
            if parent:
                parents.setdefault(parent, []).append(receipt["event_id"])
        forks = {parent: children for parent, children in parents.items()
                 if len(children) > 1}
        depth = max((receipts.DEPTHS.get(r.get("evidence_depth"), 0) for r in group),
                    default=0)
        rows.append({
            "study": key,
            "receipts": [r["event_id"] for r in group],
            "union": union,
            "forks": forks,
            "deepest": max(group, key=lambda r: receipts.DEPTHS.get(
                r.get("evidence_depth"), 0))["evidence_depth"],
            "depth_rank": depth,
        })
    return rows


def render(rows: list[dict], disease: str) -> str:
    lines = [HEADER.replace("{disease}", disease), ""]
    forked = [row for row in rows if row["forks"]]
    lines.append(f"**{len(rows)} paper(s)** with at least one receipt · "
                 f"**{sum(len(row['receipts']) for row in rows)} receipt(s)** · "
                 f"**{len(forked)} paper(s) read in parallel** by two receipts sharing a "
                 f"parent.")
    lines.append("")
    if forked:
        lines.append("## Papers read in parallel")
        lines.append("")
        lines.append("Two receipts naming one parent. Neither supersedes the other; the union "
                     "below is the state, and no single receipt states it.")
        lines.append("")
        lines.append("| paper | shared parent | siblings |")
        lines.append("|---|---|---|")
        for row in forked:
            for parent, children in sorted(row["forks"].items()):
                lines.append(f"| {row['study']} | `{parent}` | "
                             + ", ".join(f"`{child}`" for child in children) + " |")
        lines.append("")
    lines.append("## Union of coverage, per paper")
    lines.append("")
    lines.append("| paper | deepest receipt | " + " | ".join(SECTION_ORDER) + " | receipts |")
    lines.append("|---" * (len(SECTION_ORDER) + 3) + "|")
    for row in rows:
        cells = [row["union"].get(section, "—") for section in SECTION_ORDER]
        lines.append(f"| {row['study']} | `{row['deepest']}` | " + " | ".join(cells)
                     + f" | {len(row['receipts'])} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def build(root: Path, disease: str) -> str:
    ledger = receipts.load_ledger(receipts.default_ledger_path(root, disease))
    return render(summarise(ledger), disease)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=str(ROOT))
    parser.add_argument("--disease", default="wwox")
    parser.add_argument("--out", default="")
    parser.add_argument("--check", default="",
                        help="compare a committed page against a fresh derivation; "
                             "exit non-zero on drift and write nothing")
    args = parser.parse_args()
    page = build(Path(args.root).resolve(), args.disease)
    if args.check:
        committed = Path(args.check)
        if not committed.is_file():
            print(f"MISSING: {committed}")
            return 1
        if committed.read_text(encoding="utf-8") != page:
            print(f"DRIFT: {committed} no longer matches the receipt ledger")
            return 1
        print(f"CURRENT: {committed}")
        return 0
    if args.out:
        Path(args.out).write_text(page, encoding="utf-8")
        print(f"written: {args.out}")
    else:
        sys.stdout.write(page)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
