#!/usr/bin/env python3
"""Every committed generated file must be regenerated by the batch-commit protocol.

A generated file that is *committed* has a lifecycle problem the generator cannot solve on
its own: the moment its sources change it is stale, and it stays stale until somebody
remembers to rerun the command printed in its own header. `coverage_report.md` already ships
a regression that re-derives it and fails on drift — but a drift test alone fires *after* the
batch that caused the drift, announcing a defect the protocol was allowed to create.

Phase 4.7 of `prompt_batch_commit.md` closes that by regenerating inside the
snapshot-protected window. This test is what stops Phase 4.7 from decaying into prose: it
discovers the generated files rather than listing them, so the next one added to the
repository fails the suite until the protocol names it too.

It found its own first case. Phase 4.7 was written naming `coverage_report.py`, and this
check immediately reported `batch_queue.md` — a second committed generated surface, derived
from the same registries, that the protocol did not regenerate.

Run: `python3 scripts/test_generated_surfaces_are_regenerated.py`
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTOCOL = ROOT / "framework" / "protocols" / "prompt_batch_commit.md"
MARKER = "Generated file"
SKIP_PARTS = {".git", "__pycache__", ".venv", "venv", "node_modules", "backup", "staging"}
# The regeneration command a generated file prints in its own header.
COMMAND = re.compile(r"python3\s+(framework/scripts/[\w./-]+\.py)")
PHASE = re.compile(r"#### 4\.7(.*?)(?=\n> \*\*If even a single change fails)", re.S)


def markdown_files() -> list[Path]:
    return sorted(
        path for path in ROOT.rglob("*.md")
        if not any(part in SKIP_PARTS for part in path.relative_to(ROOT).parts)
    )


def generated_surfaces() -> dict[Path, set[str]]:
    """Committed Markdown that declares itself generated, mapped to its generator scripts."""
    found: dict[Path, set[str]] = {}
    for path in markdown_files():
        head = "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[:15])
        if MARKER not in head:
            continue
        scripts = set(COMMAND.findall(head))
        if scripts:
            found[path] = scripts
    return found


class GeneratedSurfaceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.surfaces = generated_surfaces()
        match = PHASE.search(PROTOCOL.read_text(encoding="utf-8"))
        self.assertIsNotNone(
            match, "prompt_batch_commit.md no longer has a Phase 4.7 regeneration step; "
                   "a committed generated file would go stale on every batch")
        self.phase = match.group(1)

    def test_at_least_one_generated_surface_is_discovered(self) -> None:
        """Guards the discovery itself: a matcher that finds nothing would pass everything."""
        self.assertTrue(
            self.surfaces,
            "no committed file declares itself generated — either the marker wording "
            "changed or this check has stopped looking at anything")

    def test_every_generated_surface_is_regenerated_by_the_protocol(self) -> None:
        missing = {
            str(path.relative_to(ROOT)): sorted(scripts)
            for path, scripts in self.surfaces.items()
            if not any(script in self.phase for script in scripts)
        }
        self.assertEqual(
            missing, {},
            "these committed files declare themselves generated but Phase 4.7 of "
            "prompt_batch_commit.md does not regenerate them, so a batch commit leaves "
            "them stale: " + ", ".join(sorted(missing)))

    def test_the_protocol_only_names_generators_that_exist(self) -> None:
        """The mirror of the above: a phase naming a deleted script is a silent no-op."""
        for script in set(COMMAND.findall(self.phase)):
            self.assertTrue((ROOT / script).is_file(),
                            f"Phase 4.7 regenerates {script}, which does not exist")


if __name__ == "__main__":
    unittest.main(verbosity=2)
