#!/usr/bin/env python3
"""Every committed generated file must be regenerated by the batch-commit protocol.

A generated file that is *committed* has a lifecycle problem the generator cannot solve on
its own: the moment its sources change it is stale, and it stays stale until somebody
remembers to rerun the command printed in its own header. `coverage_report.md` already ships
a regression that re-derives it and fails on drift — but a drift test alone fires *after* the
batch that caused the drift, announcing a defect the protocol was allowed to create.

Phase 4.7 of `prompt_batch_commit.md` closes that by regenerating inside the
snapshot-protected window. This test is what stops Phase 4.7 from decaying into prose: it
discovers the generated files rather than listing them, so the next one added to the
repository fails the suite until the protocol names it too.

It found its own first case. Phase 4.7 was written naming `coverage_report.py`, and this
check immediately reported `batch_queue.md` — a second committed generated surface, derived
from the same registries, that the protocol did not regenerate.

Run: `python3 scripts/test_generated_surfaces_are_regenerated.py`
"""

from __future__ import annotations

import os
import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTOCOL = ROOT / "framework" / "protocols" / "prompt_batch_commit.md"
# Case-insensitive, and not tied to one phrasing. Until 2026-09-14 this was the literal
# "Generated file", and `reading_state.md` opens `<!-- GENERATED by framework/scripts/...`:
# a committed derived surface this suite could not see, absent from Phase 4.7, which drifted
# the day three receipts landed. A marker that one author's capitalisation defeats is a
# discovery that silently shrinks. A header must ALSO print a `python3 framework/scripts/`
# regeneration command to count, so widening the word does not admit prose that merely
# mentions generation.
MARKER = re.compile(r"\bgenerated\b", re.I)
SKIP_PARTS = {".git", "__pycache__", ".venv", "venv", "node_modules", "backup", "staging"}
# The regeneration command a generated file prints in its own header. Any `.../scripts/*.py`,
# not only `framework/scripts/`: on 2026-09-27 the DisMech sidecar — generated by
# `disease-models/wwox/analysis/scripts/derive_dismech_sidecar.py` — was found absent from
# Phase 4.7 after a batch drifted it, and a discovery that can only see one directory of
# generators would have missed the next one too. Widening this found nothing new by itself
# (see `declared_surfaces` for why), which is the honest result of widening it anyway.
COMMAND = re.compile(r"python3\s+((?:[\w.-]+/)*scripts/[\w./-]+\.py)")
# Text formats a generated surface can be. Not only Markdown: a derived surface may be data.
SUFFIXES = (".md", ".jsonl", ".json", ".yaml", ".yml")
PHASE = re.compile(r"#### 4\.7(.*?)(?=\n> \*\*If even a single change fails)", re.S)


def text_files(root: Path = ROOT) -> list[Path]:
    """Candidate surface files of THIS checkout only.

    A directory below the root that holds its own `.git` (file or directory) is another
    checkout — a nested worktree under `.claude/worktrees/` — and its files are not the tree
    under test. Until 2026-09-14 this walked them: 40 surfaces found where the checkout has 4,
    so a stale peer worktree could turn this suite red, or a stale copy could satisfy it.
    Same pruning rule `run_release_regressions.discover_tests` already applies to archives.
    """
    found: list[Path] = []
    for directory, children, files in os.walk(root):
        here = Path(directory)
        children[:] = [child for child in children
                       if child not in SKIP_PARTS
                       and not (here / child / ".git").exists()
                       and not (here / child).is_symlink()]
        found.extend(here / name for name in files if name.endswith(SUFFIXES))
    return sorted(found)


# Kept as an alias: `markdown_files` was this function's name until 2026-09-27 and other tools
# may still ask for it by that name.
markdown_files = text_files


def self_declaring_surfaces(root: Path = ROOT) -> dict[Path, set[str]]:
    """Committed files that declare themselves generated, mapped to their generator scripts."""
    found: dict[Path, set[str]] = {}
    for path in text_files(root):
        head = "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[:15])
        if not MARKER.search(head):
            continue
        scripts = set(COMMAND.findall(head))
        if scripts:
            found[path] = scripts
    return found


def declared_surfaces(root: Path = ROOT) -> dict[Path, set[str]]:
    """The second discovery source: surfaces a generator DECLARES it produces.

    A self-declaring header is the better mechanism and stays the default — the file carries its
    own regeneration command, so a reader who finds it stale knows what to run. But it cannot be
    universal: the DisMech Phase-2 sidecar is a `.jsonl` whose every byte is pinned by a sealed
    baseline (`dismech_phase2_baseline.json`), so adding a provenance line to it would change the
    hash a seal exists to fix. Such a surface can still be *declared*, in
    `candidate_tree_freshness.py`'s `GENERATORS` — the same table the landing check already
    requires — and declaring it is what makes it discoverable here.

    Imported lazily: `candidate_tree_freshness` imports this module at module scope, and the
    declaration table is only needed when a discovery actually runs.
    """
    sys.path.insert(0, str(ROOT / "framework" / "scripts"))
    import candidate_tree_freshness  # noqa: PLC0415  (see the docstring)

    return {root / surface: set(scripts) for surface, scripts
            in candidate_tree_freshness.declared_surfaces(root).items()}


def generated_surfaces(root: Path = ROOT) -> dict[Path, set[str]]:
    """Every committed generated surface of ``root``, mapped to its generator scripts.

    ``root`` is the tree to discover in. `candidate_tree_freshness.py` passes the materialized
    candidate tree, so the landing check and this suite share ONE discovery: a surface this
    suite would demand in Phase 4.7 is a surface the landing check verifies.
    """
    found = self_declaring_surfaces(root)
    for path, scripts in declared_surfaces(root).items():
        found.setdefault(path, set()).update(scripts)
    return found


class GeneratedSurfaceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.surfaces = generated_surfaces()
        match = PHASE.search(PROTOCOL.read_text(encoding="utf-8"))
        self.assertIsNotNone(
            match, "prompt_batch_commit.md no longer has a Phase 4.7 regeneration step; "
                   "a committed generated file would go stale on every batch")
        self.phase = match.group(1)

    def test_at_least_one_generated_surface_is_discovered(self) -> None:
        """Guards the discovery itself: a matcher that finds nothing would pass everything."""
        self.assertTrue(
            self.surfaces,
            "no committed file declares itself generated — either the marker wording "
            "changed or this check has stopped looking at anything")

    def test_the_declaration_source_is_not_silently_empty(self) -> None:
        """Guards the second source the way the first one is guarded.

        `declared_surfaces` is a table read at runtime: a renamed field or a typo'd path would
        make it return nothing, and nothing passes everything. It has held at least one entry —
        the DisMech sidecar — since 2026-09-27.
        """
        self.assertTrue(
            declared_surfaces(),
            "no generator declares a surface in candidate_tree_freshness.GENERATORS — either "
            "the `surfaces` field was renamed or its declared paths no longer exist")

    def test_every_discovered_surface_has_a_declared_generator(self) -> None:
        """The landing check reports an undeclared generator as CHECK_ERROR *by design*.

        That is the right behaviour at landing time and the wrong moment to learn it: a surface
        added to the repository without a `GENERATORS` declaration turns every peer's landing
        into a tool error. Asserting it here fails the author of the surface instead. This is the
        check that was missing when the DisMech sidecar was neither declared nor regenerated.
        """
        sys.path.insert(0, str(ROOT / "framework" / "scripts"))
        import candidate_tree_freshness  # noqa: PLC0415

        declared = candidate_tree_freshness.expand_generators(ROOT)
        undeclared = {
            str(path.relative_to(ROOT)): sorted(scripts)
            for path, scripts in self.surfaces.items()
            if not any(script in declared for script in scripts)
        }
        self.assertEqual(
            undeclared, {},
            "these generated surfaces have no generator declared in "
            "framework/scripts/candidate_tree_freshness.py GENERATORS, so every landing "
            "reports them CHECK_ERROR: " + ", ".join(sorted(undeclared)))

    def test_every_generated_surface_is_regenerated_by_the_protocol(self) -> None:
        missing = {
            str(path.relative_to(ROOT)): sorted(scripts)
            for path, scripts in self.surfaces.items()
            if not any(script in self.phase for script in scripts)
        }
        self.assertEqual(
            missing, {},
            "these committed files declare themselves generated but Phase 4.7 of "
            "prompt_batch_commit.md does not regenerate them, so a batch commit leaves "
            "them stale: " + ", ".join(sorted(missing)))

    def test_the_protocol_only_names_generators_that_exist(self) -> None:
        """The mirror of the above: a phase naming a deleted script is a silent no-op."""
        for script in set(COMMAND.findall(self.phase)):
            self.assertTrue((ROOT / script).is_file(),
                            f"Phase 4.7 regenerates {script}, which does not exist")


if __name__ == "__main__":
    unittest.main(verbosity=2)
